// Source: "Pharmacy Workflows, Challenges & AI Interventions" — selected
// hospital pharmacy units. Content condensed for the Hospital Units module.

export const HOSPITAL_UNITS = [
  {
    id: "gopd",
    name: "GOPD Pharmacy",
    tag: "General Outpatient",
    primaryFunction: "Prescription & medication safety screening",
    demoHighlight: "Prescription Checker",
    workflow: [
      "Prescription received via SmartClinic, or on paper during network failure",
      "Screened for dose, frequency, interactions, duplication & appropriateness",
      "Medication availability confirmed",
      "Medication billed; patient proceeds to the payment point",
      "Payment verified; medication dispensed with directions & counselling",
      "Low or exhausted stock triggers a requisition",
      "Daily stock-take for inventory control and discrepancy detection",
    ],
    challenges: [
      "Inadequate staffing against high patient volume",
      "Network problems delaying prescription access",
      "Duplicate prescriptions from prescribers",
      "Limited time to verify interactions from reliable sources",
      "Language barriers during patient counselling",
    ],
    aiInterventions: [
      "AI-assisted screening for interactions, duplication, dose issues & DTPs",
      "AI drug information assistant with source verification",
      "Multilingual counselling support for patient-friendly instructions",
      "Predictive inventory alerts as medicines near reorder level",
    ],
    webAppDemos: [
      "Prescription screening",
      "Drug interaction checker",
      "Duplicate prescription detection",
      "AI drug information assistant",
      "Stock prediction & alerts",
    ],
  },
  {
    id: "nhis",
    name: "NHIS Pharmacy",
    tag: "Insurance Scheme",
    primaryFunction: "Prescription & billing verification",
    demoHighlight: "Billing & Error Dashboard",
    workflow: [
      "Patient identification information entered",
      "Prescription accessed and screened for errors, interactions & indication",
      "Required quantity calculated",
      "Bill raised; invoice/receipt number documented",
      "Patient presents evidence of payment",
      "Payment verified, medication dispensed, patient counselled",
    ],
    challenges: [
      "Insufficient workforce and computer workstations",
      "Poor network connectivity between pharmacy & payment point",
      "Payment or bill information delayed in the system",
      "Electricity interruptions",
      "Medication errors and documentation delays",
    ],
    aiInterventions: [
      "Automated prescription error & interaction screening",
      "Quantity calculation compared against prescribed quantities",
      "Billing and dispensing discrepancy detection",
      "Workload and queue analytics for high-demand periods",
    ],
    webAppDemos: [
      "AI prescription checker",
      "Quantity calculator",
      "Billing verification",
      "Prescription error dashboard",
      "Queue analytics",
    ],
  },
  {
    id: "og",
    name: "O&G Pharmacy",
    tag: "Obstetrics & Gynaecology",
    primaryFunction: "Surgical supply & documentation support",
    demoHighlight: "Surgical Checklist",
    workflow: [
      "Support elective and emergency surgical procedures",
      "Attend to antenatal services",
      "Supply medicines & consumables to theatre; sterile gauze to CSSD",
      "Participate in ward rounds and patient clerking",
      "Process surgical items and NHIS-related supplies",
    ],
    challenges: [
      "Wrong surgery type or request received",
      "Difficulty tracking financial losses on unpaid NHIS surgical items",
      "Communication gaps with doctors",
      "Documentation and backup-record challenges",
      "Emergency workload requiring rapid response",
    ],
    aiInterventions: [
      "Procedure-based supply checklist, alerting on mismatched surgery type",
      "Tracking of supplied, billed, paid & outstanding items",
      "Structured digital requests with AI-flagged missing information",
      "Automated documentation and audit trails",
    ],
    webAppDemos: [
      "Surgical supply checklist",
      "Request mismatch detection",
      "NHIS / payment tracker",
      "Digital request system",
      "Automated documentation",
    ],
  },
  {
    id: "theatre",
    name: "Theatre Pharmacy",
    tag: "Operating Room",
    primaryFunction: "Procedure-based supply & stock management",
    demoHighlight: "Theatre Request Dashboard",
    workflow: [
      "Receive requests from theatre; prepare medicines & consumables",
      "Check availability and issue requested items",
      "Process billing and document items issued",
      "Update stock and coordinate with the operating room",
    ],
    challenges: [
      "Out-of-stock items",
      "Cumbersome documentation",
      "SmartClinic network problems",
      "Billing issues",
      "Unstructured collection of items",
      "Poor integration between pharmacy and the operating room",
    ],
    aiInterventions: [
      "Predictive stock monitoring with early stock-out alerts",
      "Procedure-based theatre supply checklists",
      "Automated documentation of items issued per procedure",
      "Centralized OR–pharmacy request & status dashboard",
      "Emergency request prioritization",
    ],
    webAppDemos: [
      "Theatre request dashboard",
      "Procedure-based checklist",
      "Stock prediction",
      "Smart item collection",
      "OR–pharmacy integration",
    ],
  },
  {
    id: "bulkstore",
    name: "Pharmacy Bulk Store",
    tag: "Central Inventory",
    primaryFunction: "Predictive inventory & replenishment",
    demoHighlight: "Inventory Dashboard",
    workflow: [
      "Receive requisitions from stores & dispensaries via SmartClinic EMR",
      "Review and approve requisitions against stock & operational needs",
      "Check physical and system stock availability",
      "Pick and verify requested items",
      "Issue items and generate a Store Issue Voucher (SIV)",
      "Update inventory and maintain stock-card / Tally Card records",
      "Receive supplies against delivery note, invoice & quantity",
      "Shelve and store items using stock-rotation principles",
      "Reconcile physical stock with EMR and stock records",
      "Initiate replenishment when stock is low or exhausted",
    ],
    challenges: [
      "Manual, time-consuming stock monitoring",
      "Mismatches between physical stock, stock cards & EMR",
      "Stock-outs and risk of overstocking",
      "Difficulty tracking expiry across large inventories",
      "Cumbersome requisition & documentation processes",
      "Staff workload during picking, issuing & reconciliation",
      "Network/system downtime affecting EMR processes",
      "Difficulty identifying unusual stock variances or pilferage",
    ],
    aiInterventions: [
      "Predictive inventory management from consumption trends",
      "AI reorder recommendations based on demand & lead time",
      "Expiry monitoring, prioritizing items nearing expiry",
      "Requisition analysis flagging unusually high or low quantities",
      "Stock variance detection across physical, EMR & expected quantities",
      "AI-assisted receiving to flag order/invoice/delivery discrepancies",
      "Natural-language inventory search and automated stock alerts",
    ],
    webAppDemos: [
      "Predictive inventory dashboard",
      "Reorder recommendations",
      "Expiry dashboard",
      "Requisition analyzer",
      "Stock variance dashboard",
      "Receiving discrepancy checker",
      "Smart inventory search",
    ],
  },
];

// Shared "Core Dashboard" — the metrics the integrated app surfaces across
// all five units in a single pharmacy-intelligence view.
export const CORE_DASHBOARD_METRICS = [
  { label: "Prescriptions Screened", value: 1284, iconKey: "screened" },
  { label: "Medication Safety Alerts", value: 63, iconKey: "alerts" },
  { label: "Low-Stock / Predicted Stock-Outs", value: 22, iconKey: "stock" },
  { label: "Items Approaching Expiry", value: 17, iconKey: "expiry" },
  { label: "Billing Discrepancies", value: 9, iconKey: "billing" },
  { label: "Stock Variances Flagged", value: 5, iconKey: "variance" },
  { label: "Pending Requisitions & Theatre Requests", value: 34, iconKey: "requests" },
];

export const DEMONSTRATION_FLOW = [
  { title: "Screen a prescription", detail: "Enter or upload a prescription — AI identifies potential medication-related problems." },
  { title: "Generate a supply checklist", detail: "Select a surgical procedure — the system builds a pharmacy supply checklist." },
  { title: "Predict inventory needs", detail: "View inventory — AI predicts stock-outs and recommends replenishment." },
  { title: "Open the intelligence dashboard", detail: "See medication safety, inventory, billing and workflow alerts in one place." },
];

export function getUnitById(id) {
  return HOSPITAL_UNITS.find((u) => u.id === id);
}
