"use client";
import { useState } from "react";
import { FiUsers, FiAlertTriangle, FiSliders, FiShieldOff, FiMessageCircle, FiBell, FiZap } from "react-icons/fi";
import NavBar from "@/components/NavBar";
import { PageHeader, GlowCard, AnimatedCounter, FadeIn, PrimaryButton, LiveThinking, AIErrorNote, LiveModeNote } from "@/components/ui";
import { HOSPITAL_STATS } from "@/lib/miscData";
import { useApp } from "@/context/AppContext";
import { askAI } from "@/lib/aiClient";

const ICONS = [FiUsers, FiAlertTriangle, FiSliders, FiShieldOff, FiMessageCircle, FiBell];
const COLORS = ["text-ai-cyan", "text-warn", "text-hospital-blue", "text-mint", "text-ai-violet", "text-danger"];

const DASHBOARD_SYSTEM_PROMPT = `You are summarizing a hospital pharmacy's daily AI-assisted activity for a leadership briefing. Given today's simulated stats, write a concise (under 90 words) plain-language summary highlighting what stands out. No markdown, no JSON.`;

export default function HospitalDashboardPage() {
  const [liveText, setLiveText] = useState(null);
  const [liveLoading, setLiveLoading] = useState(false);
  const [liveError, setLiveError] = useState(null);
  const { liveMode } = useApp();

  async function summarize() {
    setLiveError(null);
    setLiveLoading(true);
    setLiveText(null);
    try {
      const text = await askAI(
        `Today's stats: ${HOSPITAL_STATS.map((s) => `${s.label}: ${s.value}`).join(", ")}`,
        { system: DASHBOARD_SYSTEM_PROMPT, maxTokens: 250 }
      );
      setLiveText(text);
    } catch (e) {
      setLiveError(e.message);
    } finally {
      setLiveLoading(false);
    }
  }

  return (
    <>
      <NavBar />
      <main className="flex-1 max-w-5xl w-full mx-auto px-6 py-10">
        <PageHeader
          eyebrow="Hospital Dashboard"
          title="Today at a Glance"
          subtitle="A simulated live view of AI-assisted pharmacy activity across the hospital today."
        />
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mb-6">
          {HOSPITAL_STATS.map((s, i) => {
            const Icon = ICONS[i];
            return (
              <FadeIn key={s.label} delay={i * 0.08}>
                <GlowCard className="text-center py-8">
                  <Icon className={`mx-auto mb-3 ${COLORS[i]}`} size={26} />
                  <div className="text-4xl font-bold text-white mb-1">
                    <AnimatedCounter value={s.value} suffix={s.suffix} />
                  </div>
                  <div className="text-xs text-slate-400">{s.label}</div>
                </GlowCard>
              </FadeIn>
            );
          })}
        </div>

        {liveMode && (
          <GlowCard>
            <PrimaryButton onClick={summarize} disabled={liveLoading} className="flex items-center gap-2 mb-3">
              <FiZap size={14} /> Ask Live AI to Summarize Today
            </PrimaryButton>
            {liveLoading && <LiveThinking label="Summarizing with Claude..." />}
            {liveError && <AIErrorNote message={liveError} onRetry={summarize} />}
            {liveText && (
              <FadeIn>
                <LiveModeNote>Live AI Mode — generated by Claude, not scripted</LiveModeNote>
                <p className="text-[13px] text-slate-200 leading-relaxed p-3 rounded-lg bg-ai-cyan/5 border border-ai-cyan/20">{liveText}</p>
              </FadeIn>
            )}
          </GlowCard>
        )}
      </main>
    </>
  );
}
